# Generated by Django 2.1.1 on 2018-09-19 12:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('shop_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landmarks', models.CharField(max_length=2500)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 9, 19, 12, 44, 5, 800589, tzinfo=utc))),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faces_in_shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', models.IntegerField(default=1)),
                ('time', models.DateTimeField(default=datetime.datetime(2018, 9, 19, 12, 44, 5, 801175, tzinfo=utc))),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Faces')),
            ],
        ),
        migrations.CreateModel(
            name='Locals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='shop_uuid')),
            ],
        ),
        migrations.AddField(
            model_name='faces_in_shops',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Locals'),
        ),
        migrations.AddField(
            model_name='faces_in_shops',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='shop_uuid'),
        ),
    ]
