# Generated by Django 2.1 on 2018-09-06 16:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faces',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 6, 16, 20, 19, 554824, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faces_in_shops',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 6, 16, 20, 19, 555258, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shops',
            name='shop_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
