# Generated by Django 2.1 on 2018-09-07 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20180906_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faces',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 7, 9, 11, 36, 682460, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faces_in_shops',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 7, 9, 11, 36, 682971, tzinfo=utc)),
        ),
    ]
